top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/mappers
builddir     = /home/shaowy/ab_fork/modules/mappers
VPATH        = /home/shaowy/ab_fork/modules/mappers

include $(top_srcdir)/build/special.mk

