top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/metadata
builddir     = /home/shaowy/ab_fork/modules/metadata
VPATH        = /home/shaowy/ab_fork/modules/metadata

include $(top_srcdir)/build/special.mk

