top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/loggers
builddir     = /home/shaowy/ab_fork/modules/loggers
VPATH        = /home/shaowy/ab_fork/modules/loggers

include $(top_srcdir)/build/special.mk

