top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/generators
builddir     = /home/shaowy/ab_fork/modules/generators
VPATH        = /home/shaowy/ab_fork/modules/generators

include $(top_srcdir)/build/special.mk

