top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/echo
builddir     = /home/shaowy/ab_fork/modules/echo
VPATH        = /home/shaowy/ab_fork/modules/echo

include $(top_srcdir)/build/special.mk

