top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/filters
builddir     = /home/shaowy/ab_fork/modules/filters
VPATH        = /home/shaowy/ab_fork/modules/filters

include $(top_srcdir)/build/special.mk

