top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/aaa
builddir     = /home/shaowy/ab_fork/modules/aaa
VPATH        = /home/shaowy/ab_fork/modules/aaa

include $(top_srcdir)/build/special.mk

