top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/lua
builddir     = /home/shaowy/ab_fork/modules/lua
VPATH        = /home/shaowy/ab_fork/modules/lua
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
