top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/server/mpm/event
builddir     = /home/shaowy/ab_fork/server/mpm/event
VPATH        = /home/shaowy/ab_fork/server/mpm/event
include $(top_srcdir)/build/special.mk
