top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/cache
builddir     = /home/shaowy/ab_fork/modules/cache
VPATH        = /home/shaowy/ab_fork/modules/cache

include $(top_srcdir)/build/special.mk

