top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/os
builddir     = /home/shaowy/ab_fork/os
VPATH        = /home/shaowy/ab_fork/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
