top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/arch/unix
builddir     = /home/shaowy/ab_fork/modules/arch/unix
VPATH        = /home/shaowy/ab_fork/modules/arch/unix

include $(top_srcdir)/build/special.mk

