top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/core
builddir     = /home/shaowy/ab_fork/modules/core
VPATH        = /home/shaowy/ab_fork/modules/core

include $(top_srcdir)/build/special.mk

