top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/modules/http
builddir     = /home/shaowy/ab_fork/modules/http
VPATH        = /home/shaowy/ab_fork/modules/http

include $(top_srcdir)/build/special.mk

