top_srcdir   = /home/shaowy/ab_fork
top_builddir = /home/shaowy/ab_fork
srcdir       = /home/shaowy/ab_fork/server/mpm
builddir     = /home/shaowy/ab_fork/server/mpm
VPATH        = /home/shaowy/ab_fork/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
